#!/usr/bin/env python3

import json
from pprint import pprint
import sys



with open('swordsman.json') as f:
    data = json.load(f)
f.close()

print("""
    name:   {name}
    speed:    {speed}
    defence:    {defence}
""".format(**data))
